# Generated by Django 4.0.10 on 2025-03-10 04:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'permissions': [('can_create_service', 'Can create service'), ('can_edit_service', 'Can edit service'), ('can_delete_service', 'Can delete service')],
            },
        ),
    ]
