# Generated by Django 4.0.10 on 2025-04-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
    ]
