# Generated by Django 4.0.10 on 2025-05-18 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter Egyptian number (e.g.: +201234567890 or 01234567890)', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be Egyptian (e.g.: +201234567890, 01234567890, or 1234567890)', regex='^(\\+20|0)?1[0-9]{9}$')]),
        ),
    ]
