# Generated by Django 4.0.10 on 2025-06-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0016_review'),
        ('accounts', '0005_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='craftsmen.craftsman'),
        ),
    ]
