# Generated by Django 4.0.10 on 2025-03-10 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('craftsmen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='id',
        ),
        migrations.AddField(
            model_name='craftsman',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='photo',
            field=models.ImageField(upload_to='craftsmen'),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
