# Generated by Django 4.0.10 on 2025-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0002_remove_craftsman_id_craftsman_address_craftsman_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='craftsmen'),
        ),
    ]
