# Generated by Django 4.0.10 on 2025-03-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0003_alter_craftsman_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
