# Generated by Django 4.0.10 on 2025-03-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0005_remove_craftsman_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='address',
        ),
        migrations.AddField(
            model_name='craftsman',
            name='governorate',
            field=models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('giza', 'Giza'), ('sharkia', 'Sharkia'), ('dakahlia', 'Dakahlia'), ('beheira', 'Beheira'), ('qalyubia', 'Qalyubia'), ('monufia', 'Monufia'), ('gharbia', 'Gharbia'), ('sohag', 'Sohag'), ('aswan', 'Aswan'), ('luxor', 'Luxor'), ('ismailia', 'Ismailia'), ('port_said', 'Port Said'), ('suez', 'Suez'), ('damietta', 'Damietta'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('matrouh', 'Matrouh'), ('north_sinai', 'North Sinai'), ('south_sinai', 'South Sinai'), ('red_sea', 'Red Sea'), ('new_valley', 'New Valley'), ('faiyum', 'Faiyum'), ('beni_suef', 'Beni Suef'), ('minya', 'Minya'), ('assiut', 'Assiut'), ('qena', 'Qena')], max_length=50, null=True),
        ),
    ]
