# Generated by Django 4.0.10 on 2025-03-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0006_remove_craftsman_address_craftsman_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
