# Generated by Django 4.0.10 on 2025-04-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0007_craftsman_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='craftsman',
            table='craftsmen',
        ),
    ]
