# Generated by Django 4.0.10 on 2025-05-29 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('craftsmen', '0010_alter_comment_options_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_craftsmen', to=settings.AUTH_USER_MODEL),
        ),
    ]
