# Generated by Django 4.0.10 on 2025-05-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0012_bookingrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftsman',
            options={'ordering': ['rating']},
        ),
    ]
