# Generated by Django 4.0.10 on 2025-06-02 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0013_alter_craftsman_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftsman',
            options={'ordering': ['-rating']},
        ),
    ]
