# Generated by Django 4.0.10 on 2025-06-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmen', '0016_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='craftsman',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
